services:
  backend:
    build:
      context: ./ERAS-BE
      dockerfile: ./src/Presentation/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    volumes:
      - /app/node_modules
    depends_on:
      - database
    networks:
      - eras_network

  frontend:
    build:
      context: ./ERAS-FE
    ports:
      - "4200:80"
    volumes:
      - ./ERAS-FE:/app
    depends_on:
      - backend
    networks:
      - eras_network

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: eras_user
      POSTGRES_PASSWORD: eras_password
      POSTGRES_DB: eras_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eras_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 18080:8080
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - eras_network

volumes:
  postgres_data:
  keycloak_data:

networks:
  eras_network:
