services:
  backend:
    build:
      context: ./ERAS-BE
      dockerfile: ./src/Eras.Api/Dockerfile
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080

      # Database Connection
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
    networks:
      - eras_network

  frontend:
    build:
      context: ./ERAS-FE
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./ERAS-FE:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - eras_network

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eras_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: ${POSTGRES_HEALTHCHECK_INTERVAL}
      timeout: ${POSTGRES_HEALTHCHECK_TIMEOUT}
      retries: ${POSTGRES_HEALTHCHECK_RETRIES}
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start-dev --verbose --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - 18080:8080
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./Keycloak/:/opt/keycloak/data/import
    networks:
      - eras_network

volumes:
  postgres_data:
  keycloak_data:

networks:
  eras_network:
