# File location: ~/app
services:
  backend:
    image: erasadmin/eras-be:${BE_VERSION}
    ports:
      - "${BACKEND_PORT}:443"
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

      # Database Connection
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /app/node_modules
      - /home/ubuntu/ssl-certificates/eras-backend.pfx:/https/aspnetapp.pfx:ro
    depends_on:
      database:
        condition: service_healthy
    networks:
      - eras_network
    deploy:
      resources:
        limits:
          cpus: '0.4'   # Max 40% de la CPU
          memory: '400M' # Max 400 MB de RAM

  frontend:
    image: erasadmin/eras-fe:${FE_VERSION}
    ports:
      - "${FRONTEND_PORT}:80"
      - "443:443"
    networks:
      - eras_network
    depends_on:
      - backend
    volumes:
      - /home/ubuntu/ssl-certificates/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/ssl-certificates/eras.crt:/etc/nginx/ssl/eras.crt
      - /home/ubuntu/ssl-certificates/eras.key:/etc/nginx/ssl/eras.key
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '200M'

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - eras_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eras_user -d eras_db || exit 1"]
      interval: ${POSTGRES_HEALTHCHECK_INTERVAL}
      timeout: ${POSTGRES_HEALTHCHECK_TIMEOUT}
      retries: ${POSTGRES_HEALTHCHECK_RETRIES}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '350M'

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start-dev --import-realm --verbose
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - JAVA_OPTS=-Xms256m -Xmx512m
      - KC_HTTP_ENABLED=true
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/data/eras.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/data/eras.key
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    ports:
      - 8082:8080
      - 8443:8443
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realms:/opt/keycloak/data/import
      - /home/ubuntu/ssl-certificates/eras.key:/opt/keycloak/data/eras.key
      - /home/ubuntu/ssl-certificates/eras.crt:/opt/keycloak/data/eras.crt
    networks:
      - eras_network
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '600M'

volumes:
  keycloak_data:

networks:
  eras_network: